-- create table public.customers
-- (
--     id        bigint generated by default as identity
--         primary key,
--     address   varchar(255),
--     age       integer          not null,
--     balance   double precision not null,
--     first_name varchar(255),
--     last_name varchar(255),
--     pin_code  varchar(255)
-- );


insert into customers values (1,'Baku',25,3000,'Test','Testov','111111')